// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "Overload only for more doc accuracy.", Scope = "member", Target = "~M:WinCopies.Util.BackgroundWorker.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.AddIfNotContains(System.Collections.IList,System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.AddRangeIfNotContains(System.Collections.IList,System.Collections.IEnumerable)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.AddRangeIfNotContains(System.Collections.IList,System.Collections.IEnumerable)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToList(System.Collections.IEnumerable,System.Int32@,System.Nullable{System.Int32}@)~System.Collections.ArrayList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToList``1(System.Collections.Generic.IEnumerable{``0},System.Int32@,System.Nullable{System.Int32}@)~System.Collections.Generic.List{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToArray(System.Collections.IEnumerable)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToArray(System.Collections.IEnumerable,System.Int32@,System.Int32@)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToArray``1(System.Collections.Generic.IEnumerable{``0},System.Int32@,System.Int32@)~``0[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToList(System.Object[],System.Int32@,System.Int32@)~System.Collections.ArrayList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToList``1(``0[],System.Int32@,System.Int32@)~System.Collections.Generic.List{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToArray(System.Collections.IList,System.Int32@,System.Int32@)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.ToArray``1(System.Collections.Generic.IList{``0},System.Int32@,System.Int32@)~``0[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.RemoveRange(System.Collections.IList,System.Int32@,System.Int32@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.Sort``1(System.Collections.ObjectModel.ObservableCollection{``0})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Valider les arguments de méthodes publiques", Justification = "Null check is made by the ThrowIfNull method.", Scope = "member", Target = "~M:WinCopies.Util.Extensions.Sort``1(System.Collections.ObjectModel.ObservableCollection{``0},System.Collections.Generic.IComparer{``0}@)")]
