//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCopies.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCopies.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrays must have only one dimension..
        /// </summary>
        internal static string ArrayWithMoreThanOneDimension {
            get {
                return ResourceManager.GetString("ArrayWithMoreThanOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The BackgroundWorker is busy..
        /// </summary>
        internal static string BackgroundWorkerIsBusy {
            get {
                return ResourceManager.GetString("BackgroundWorkerIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close _all tabs.
        /// </summary>
        internal static string CloseAllTabsWPF {
            get {
                return ResourceManager.GetString("CloseAllTabsWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C_lose tab.
        /// </summary>
        internal static string CloseTabWPF {
            get {
                return ResourceManager.GetString("CloseTabWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clos_e window.
        /// </summary>
        internal static string CloseWindowWPF {
            get {
                return ResourceManager.GetString("CloseWindowWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The declaring types of &apos;{0}&apos; and &apos;{1}&apos; do not correspond. The declaring types of &apos;{0}&apos; and &apos;{1}&apos; must correspond for read-only properties when an integrity check is performed..
        /// </summary>
        internal static string DeclaringTypesNotCorrespond {
            get {
                return ResourceManager.GetString("DeclaringTypesNotCorrespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Delete permanently.
        /// </summary>
        internal static string DeletePermanentlyWPF {
            get {
                return ResourceManager.GetString("DeletePermanentlyWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Deselect all.
        /// </summary>
        internal static string DeselectAllWPF {
            get {
                return ResourceManager.GetString("DeselectAllWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; couldn&apos;t be found in &apos;{1}&apos;..
        /// </summary>
        internal static string FieldOrPropertyNotFound {
            get {
                return ResourceManager.GetString("FieldOrPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enum value is not in the enum values range. The enum value is {0}..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _New archive.
        /// </summary>
        internal static string NewArchiveWPF {
            get {
                return ResourceManager.GetString("NewArchiveWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New _folder.
        /// </summary>
        internal static string NewFolderWPF {
            get {
                return ResourceManager.GetString("NewFolderWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New _tab.
        /// </summary>
        internal static string NewTabWPF {
            get {
                return ResourceManager.GetString("NewTabWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Window in a new _process.
        /// </summary>
        internal static string NewWindowInNewInstanceWPF {
            get {
                return ResourceManager.GetString("NewWindowInNewInstanceWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New _window.
        /// </summary>
        internal static string NewWindowWPF {
            get {
                return ResourceManager.GetString("NewWindowWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; must be one of the {1} enum values..
        /// </summary>
        internal static string NoValidEnumValue {
            get {
                return ResourceManager.GetString("NoValidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; has one or more same key..
        /// </summary>
        internal static string OneOrMoreSameKey {
            get {
                return ResourceManager.GetString("OneOrMoreSameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This collection is read-only..
        /// </summary>
        internal static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Rename.
        /// </summary>
        internal static string RenameWPF {
            get {
                return ResourceManager.GetString("RenameWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Reverse selection.
        /// </summary>
        internal static string ReverseSelectionWPF {
            get {
                return ResourceManager.GetString("ReverseSelectionWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File _propoerties.
        /// </summary>
        internal static string ShowFilePropertiesWPF {
            get {
                return ResourceManager.GetString("ShowFilePropertiesWPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; is empty or white spaces..
        /// </summary>
        internal static string StringParameterEmptyOrWhiteSpaces {
            get {
                return ResourceManager.GetString("StringParameterEmptyOrWhiteSpaces", resourceCulture);
            }
        }
    }
}
